spring:
  datasource:
    url: jdbc:mysql://localhost:3306/health_steward?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 3MB

server:
  port: 12345

mybatis-plus:
  type-handlers-package: com.healthsteward.util.typehandler
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
  type-aliases-package: com.healthsteward.pojo
  config-location: classpath:mybatis/mybatis-config.xml


# 将mybatis的logger级别设置为debug，这样会打印出所有运行的sql语句
#logging:
#  level:
#    com.healthsteward.mapper.*:info

